const STREAKI_CONFIG = {
  SHEET_ID: '1WrJPj5Pdms2lFV59NCVPm7eU5eLz2-eSp55MFk4qNGg',
  SHEET_MAIN_GID: '0',
  SHEET_INNE_GID: '2135936810',

  PORTRAIT_MAP: {
    'The Trapper':          'https://deadbydaylight.wiki.gg/images/K01_TheTrapper_Portrait.png',
    'The Wraith':           'https://deadbydaylight.wiki.gg/images/K02_TheWraith_Portrait.png',
    'The Hillbilly':        'https://deadbydaylight.wiki.gg/images/K03_TheHillbilly_Portrait.png',
    'The Nurse':            'https://deadbydaylight.wiki.gg/images/K04_TheNurse_Portrait.png',
    'The Shape':            'https://deadbydaylight.wiki.gg/images/K05_TheShape_Portrait.png',
    'The Hag':              'https://deadbydaylight.wiki.gg/images/K06_TheHag_Portrait.png',
    'The Doctor':           'https://deadbydaylight.wiki.gg/images/K07_TheDoctor_Portrait.png',
    'The Huntress':         'https://deadbydaylight.wiki.gg/images/K08_TheHuntress_Portrait.png',
    'The Cannibal':         'https://deadbydaylight.wiki.gg/images/K09_TheCannibal_Portrait.png',
    'The Nightmare':        'https://deadbydaylight.wiki.gg/images/K10_TheNightmare_Portrait.png',
    'The Pig':              'https://deadbydaylight.wiki.gg/images/K11_ThePig_Portrait.png',
    'The Clown':            'https://deadbydaylight.wiki.gg/images/K12_TheClown_Portrait.png',
    'The Spirit':           'https://deadbydaylight.wiki.gg/images/K13_TheSpirit_Portrait.png',
    'The Legion':           'https://deadbydaylight.wiki.gg/images/K14_TheLegion_Portrait.png',
    'The Plague':           'https://deadbydaylight.wiki.gg/images/K15_ThePlague_Portrait.png',
    'The Ghost Face':       'https://deadbydaylight.wiki.gg/images/K16_TheGhostFace_Portrait.png',
    'The Demogorgon':       'https://deadbydaylight.wiki.gg/images/K17_TheDemogorgon_Portrait.png',
    'The Oni':              'https://deadbydaylight.wiki.gg/images/K18_TheOni_Portrait.png',
    'The Deathslinger':     'https://deadbydaylight.wiki.gg/images/K19_TheDeathslinger_Portrait.png',
    'The Executioner':      'https://deadbydaylight.wiki.gg/images/K20_TheExecutioner_Portrait.png',
    'The Blight':           'https://deadbydaylight.wiki.gg/images/K21_TheBlight_Portrait.png',
    'The Twins':            'https://deadbydaylight.wiki.gg/images/K22_TheTwins_Portrait.png',
    'The Trickster':        'https://deadbydaylight.wiki.gg/images/K23_TheTrickster_Portrait.png',
    'The Nemesis':          'https://deadbydaylight.wiki.gg/images/K24_TheNemesis_Portrait.png',
    'The Cenobite':         'https://deadbydaylight.wiki.gg/images/K25_TheCenobite_Portrait.png',
    'The Artist':           'https://deadbydaylight.wiki.gg/images/K26_TheArtist_Portrait.png',
    'The Onryo':            'https://deadbydaylight.wiki.gg/images/K27_TheOnryo_Portrait.png',
    'The Dredge':           'https://deadbydaylight.wiki.gg/images/K28_TheDredge_Portrait.png',
    'The Mastermind':       'https://deadbydaylight.wiki.gg/images/K29_TheMastermind_Portrait.png',
    'The Knight':           'https://deadbydaylight.wiki.gg/images/K30_TheKnight_Portrait.png',
    'The Skull Merchant':   'https://deadbydaylight.wiki.gg/images/K31_TheSkullMerchant_Portrait.png',
    'The Singularity':      'https://deadbydaylight.wiki.gg/images/K32_TheSingularity_Portrait.png',
    'The Xenomorph':        'https://deadbydaylight.wiki.gg/images/K33_TheXenomorph_Portrait.png',
    'The Good Guy':         'https://deadbydaylight.wiki.gg/images/K34_TheGoodGuy_Portrait.png',
    'The Unknown':          'https://deadbydaylight.wiki.gg/images/K35_TheUnknown_Portrait.png',
    'The Lich':             'https://deadbydaylight.wiki.gg/images/K36_TheLich_Portrait.png',
    'The Dark Lord':        'https://deadbydaylight.wiki.gg/images/K37_TheDarkLord_Portrait.png',
    'The Houndmaster':      'https://deadbydaylight.wiki.gg/images/K38_TheHoundmaster_Portrait.png',
    'The Ghoul':            'https://deadbydaylight.wiki.gg/images/K39_TheGhoul_Portrait.png',
    'The Animatronic':      'https://deadbydaylight.wiki.gg/images/K40_TheAnimatronic_Portrait.png',
    'The Krasue':           'https://deadbydaylight.wiki.gg/images/K41_TheKrasue_Portrait.png',
    'The First':            'https://deadbydaylight.wiki.gg/images/K42_TheFirst_Portrait.png',
    'The Slasher':          'https://deadbydaylight.wiki.gg/images/K43_TheSlasher_Portrait.png',

    'Copycat':              'https://deadbydaylight.wiki.gg/images/S03_ClaudetteMorel_Portrait.png',
    'Solo Escape':          'https://deadbydaylight.wiki.gg/images/S02_MegThomas_Portrait.png',
    'Team Escape':          'https://deadbydaylight.wiki.gg/images/S01_DwightFairfield_Portrait.png'
  },

  PLACEHOLDER_IMG: 'https://via.placeholder.com/120x120/1a0a0c/8b0000?text=?',

  DEFAULT_VIEW: 'default'
};
