const STATS_CONFIG = {
  SHEET_ID: '1Lwf_RFJEeCRRUUbo6eCKwxCU1HHPSghIJpn8wfqs57c',
  SHEET_KILLERS_GID: '0',
  SHEET_SURVIVORS_GID: '322786289',
  DEFAULT_MODE: 'killers',
  PLACEHOLDER_IMG: 'https://via.placeholder.com/120x120/1a0a0c/888888?text=?',
  SHOW_CATEGORY_ICONS: true,

  CATEGORY_COLORS: {
    'Prestiż': '#6b7280',
    'Strimersy': '#22c55e',
    'Puddingi': '#86efac',
    'Muszle': '#4ade80',
    'Cake': '#fde047',
    'Frightful Flan (Anniversary 6)': '#f97316',
    'Terrormisu (Anniversary 7)': '#fb923c',
    'Screech Cobbler (Anniversary 8)': '#fdba74',
    'Coconut Scream Pie (Anniversary 9)': '#ea580c',
    'Toothy Torte (Anniversary 10)': '#c2410c',
    'Toothy Torte  (Anniversary 10)': '#c2410c',
    'Cake Rocznicowy (Anniversary 10)': '#c2410c',
    'Banquet Flashlight (The Black Banquet)': '#f97316',
    'Banquet Med-Kit (The Black Banquet)': '#fb923c',
    'Banquet Toolbox (The Black Banquet)': '#fdba74',
    'Masquerade Flashlight (Twisted Masquerade )': '#ea580c',
    'Masquerade Med-Kit (Twisted Masquerade )': '#f97316',
    'Masquerade Toolbox (Twisted Masquerade )': '#fb923c',
    'Masquerade Flashlight (Anniversary)': '#ea580c',
    'Masquerade Med-Kit (Anniversary)': '#f97316',
    'Masquerade Toolbox (Anniversary)': '#fb923c',
    'Bloodshot Eye (Blood Moon)': '#ef4444',
    'Bloodsense Map (Blood Moon)': '#dc2626',
    'Mistle Toes (Bone Chill)': '#fde68a',
    'Winter Party Starter (Bone Chill)': '#fbbf24',
    'Red Envelope (Chinski nowy rok)': '#eab308',
    'Chinese Firecracker (Chinski nowy rok)': '#facc15',
    'Festive Toolbox (Chinski nowy rok)': '#fbbf24',
    'Arcane Dowsing Rod (Halloween)': '#a855f7',
    'Blight Serum (Halloween)': '#9333ea',
    "All Hallows' Eve Lunchbox (Halloween)": '#7c3aed',
    "Will O' Wisp (Halloween)": '#8b5cf6',
    'Broken Bulb (Halloween)': '#c084fc',
    'Refined Serum (Halloween)': '#a78bfa'
  },

  CATEGORY_ICONS: {
    'Prestiż': '',
    'Strimersy': 'https://deadbydaylight.wiki.gg/images/IconFavors_bloodyPartyStreamers.png',
    'Puddingi': 'https://deadbydaylight.wiki.gg/images/IconFavors_survivorPudding.png',
    'Muszle': 'https://deadbydaylight.wiki.gg/images/IconFavors_hollowShell.png',
    'Cake': 'https://deadbydaylight.wiki.gg/images/IconFavors_escapeCake.png',
    'Frightful Flan (Anniversary 6)': 'https://deadbydaylight.wiki.gg/images/IconFavors_frightfulFlan.png',
    'Terrormisu (Anniversary 7)': 'https://deadbydaylight.wiki.gg/images/IconFavors_terrormisu.png',
    'Screech Cobbler (Anniversary 8)': 'https://deadbydaylight.wiki.gg/images/IconFavors_screechCobbler.png',
    'Coconut Scream Pie (Anniversary 9)': 'https://deadbydaylight.wiki.gg/images/IconsFavors_9thAnniversary.png',
    'Toothy Torte (Anniversary 10)': 'https://deadbydaylight.wiki.gg/images/IconsFavors_10thAnniversary.png',
    'Banquet Flashlight (The Black Banquet)': 'https://deadbydaylight.wiki.gg/images/T_UI_iconItems_flashlight_anniversary2026.png',
    'Banquet Med-Kit (The Black Banquet)': 'https://deadbydaylight.wiki.gg/images/T_UI_iconItems_medkit_anniversary2026.png',
    'Banquet Toolbox (The Black Banquet)': 'https://deadbydaylight.wiki.gg/images/T_UI_iconItems_toolbox_anniversary2026.png',
    'Masquerade Flashlight (Twisted Masquerade )': 'https://deadbydaylight.wiki.gg/images/IconItems_masqueradeFlashlight.png',
    'Masquerade Med-Kit (Twisted Masquerade )': 'https://deadbydaylight.wiki.gg/images/IconItems_masqueradeMedKit.png',
    'Masquerade Toolbox (Twisted Masquerade )': 'https://deadbydaylight.wiki.gg/images/IconItems_masqueradeToolbox.png',
    'Bloodshot Eye (Blood Moon)': 'https://deadbydaylight.wiki.gg/images/IconFavors_bloodshotEye.png',
    'Bloodsense Map (Blood Moon)': 'https://deadbydaylight.wiki.gg/images/IconItems_bloodsenseMap.png',
    'Mistle Toes (Bone Chill)': 'https://deadbydaylight.wiki.gg/images/IconsFavors_Winter.png',
    'Winter Party Starter (Bone Chill)': 'https://deadbydaylight.wiki.gg/images/IconItems_winterPartyStarter.png',
    'Red Envelope (Chinski nowy rok)': 'https://deadbydaylight.wiki.gg/images/IconFavors_redEnvelope.png',
    'Chinese Firecracker (Chinski nowy rok)': 'https://deadbydaylight.wiki.gg/images/IconItems_chineseFirecracker.png',
    'Festive Toolbox (Chinski nowy rok)': 'https://deadbydaylight.wiki.gg/images/IconItems_festiveToolbox.png',
    'Arcane Dowsing Rod (Halloween)': 'https://deadbydaylight.wiki.gg/images/IconFavors_arcaneDousingRod.png',
    'Blight Serum (Halloween)': 'https://deadbydaylight.wiki.gg/images/IconAddon_blightSerum.png',
    "All Hallows' Eve Lunchbox (Halloween)": 'https://deadbydaylight.wiki.gg/images/IconItems_allHallowsEveLunchbox.png',
    "Will O' Wisp (Halloween)": 'https://deadbydaylight.wiki.gg/images/IconItems_willOWisp.png',
    'Broken Bulb (Halloween)': 'https://deadbydaylight.wiki.gg/images/IconAddon_brokenBulb.png',
    'Refined Serum (Halloween)': 'https://deadbydaylight.wiki.gg/images/IconAddon_refinedSerum.png'
  },

  PRESTIGE_SPRITES: {
    displaySize: 48,
    sheet1: { url: 'assets/prestige1_25.png', width: 1243, height: 1193 },
    sheet2: { url: 'assets/prestige30_100.png', width: 994, height: 922 },
    levels: {
    1: { sheet: 'sheet1', x: 68, y: 84, w: 180, h: 180, label: false },
    2: { sheet: 'sheet1', x: 284, y: 84, w: 180, h: 180, label: false },
    3: { sheet: 'sheet1', x: 508, y: 84, w: 180, h: 180, label: false },
    4: { sheet: 'sheet1', x: 734, y: 84, w: 180, h: 180, label: false },
    5: { sheet: 'sheet1', x: 964, y: 84, w: 180, h: 180, label: false },
    6: { sheet: 'sheet1', x: 68, y: 298, w: 180, h: 180, label: false },
    7: { sheet: 'sheet1', x: 284, y: 298, w: 180, h: 180, label: false },
    8: { sheet: 'sheet1', x: 508, y: 298, w: 180, h: 180, label: false },
    9: { sheet: 'sheet1', x: 734, y: 298, w: 180, h: 180, label: false },
    10: { sheet: 'sheet1', x: 964, y: 298, w: 180, h: 180, label: false },
    11: { sheet: 'sheet1', x: 68, y: 514, w: 180, h: 180, label: false },
    12: { sheet: 'sheet1', x: 284, y: 514, w: 180, h: 180, label: false },
    13: { sheet: 'sheet1', x: 508, y: 514, w: 180, h: 180, label: false },
    14: { sheet: 'sheet1', x: 734, y: 514, w: 180, h: 180, label: false },
    15: { sheet: 'sheet1', x: 964, y: 514, w: 180, h: 180, label: false },
    16: { sheet: 'sheet1', x: 68, y: 728, w: 180, h: 180, label: false },
    17: { sheet: 'sheet1', x: 284, y: 728, w: 180, h: 180, label: false },
    18: { sheet: 'sheet1', x: 508, y: 728, w: 180, h: 180, label: false },
    19: { sheet: 'sheet1', x: 734, y: 728, w: 180, h: 180, label: false },
    20: { sheet: 'sheet1', x: 964, y: 728, w: 180, h: 180, label: false },
    21: { sheet: 'sheet1', x: 68, y: 944, w: 180, h: 180, label: false },
    22: { sheet: 'sheet1', x: 284, y: 944, w: 180, h: 180, label: false },
    23: { sheet: 'sheet1', x: 508, y: 944, w: 180, h: 180, label: false },
    24: { sheet: 'sheet1', x: 734, y: 944, w: 180, h: 180, label: false },
    25: { sheet: 'sheet1', x: 964, y: 944, w: 180, h: 180, label: false },
    26: { sheet: 'sheet2', x: 55, y: 55, w: 145, h: 145, label: true },
    27: { sheet: 'sheet2', x: 55, y: 55, w: 145, h: 145, label: true },
    28: { sheet: 'sheet2', x: 55, y: 55, w: 145, h: 145, label: true },
    29: { sheet: 'sheet2', x: 55, y: 55, w: 145, h: 145, label: true },
    30: { sheet: 'sheet2', x: 55, y: 55, w: 145, h: 145, label: true },
    31: { sheet: 'sheet2', x: 232, y: 55, w: 145, h: 145, label: true },
    32: { sheet: 'sheet2', x: 232, y: 55, w: 145, h: 145, label: true },
    33: { sheet: 'sheet2', x: 232, y: 55, w: 145, h: 145, label: true },
    34: { sheet: 'sheet2', x: 232, y: 55, w: 145, h: 145, label: true },
    35: { sheet: 'sheet2', x: 232, y: 55, w: 145, h: 145, label: true },
    36: { sheet: 'sheet2', x: 409, y: 55, w: 145, h: 145, label: true },
    37: { sheet: 'sheet2', x: 409, y: 55, w: 145, h: 145, label: true },
    38: { sheet: 'sheet2', x: 409, y: 55, w: 145, h: 145, label: true },
    39: { sheet: 'sheet2', x: 409, y: 55, w: 145, h: 145, label: true },
    40: { sheet: 'sheet2', x: 409, y: 55, w: 145, h: 145, label: true },
    41: { sheet: 'sheet2', x: 586, y: 55, w: 145, h: 145, label: true },
    42: { sheet: 'sheet2', x: 586, y: 55, w: 145, h: 145, label: true },
    43: { sheet: 'sheet2', x: 586, y: 55, w: 145, h: 145, label: true },
    44: { sheet: 'sheet2', x: 586, y: 55, w: 145, h: 145, label: true },
    45: { sheet: 'sheet2', x: 586, y: 55, w: 145, h: 145, label: true },
    46: { sheet: 'sheet2', x: 762, y: 55, w: 145, h: 145, label: true },
    47: { sheet: 'sheet2', x: 762, y: 55, w: 145, h: 145, label: true },
    48: { sheet: 'sheet2', x: 762, y: 55, w: 145, h: 145, label: true },
    49: { sheet: 'sheet2', x: 762, y: 55, w: 145, h: 145, label: true },
    50: { sheet: 'sheet2', x: 762, y: 55, w: 145, h: 145, label: true },
    51: { sheet: 'sheet2', x: 54, y: 272, w: 145, h: 145, label: true },
    52: { sheet: 'sheet2', x: 54, y: 272, w: 145, h: 145, label: true },
    53: { sheet: 'sheet2', x: 54, y: 272, w: 145, h: 145, label: true },
    54: { sheet: 'sheet2', x: 54, y: 272, w: 145, h: 145, label: true },
    55: { sheet: 'sheet2', x: 54, y: 272, w: 145, h: 145, label: true },
    56: { sheet: 'sheet2', x: 229, y: 272, w: 145, h: 145, label: true },
    57: { sheet: 'sheet2', x: 229, y: 272, w: 145, h: 145, label: true },
    58: { sheet: 'sheet2', x: 229, y: 272, w: 145, h: 145, label: true },
    59: { sheet: 'sheet2', x: 229, y: 272, w: 145, h: 145, label: true },
    60: { sheet: 'sheet2', x: 229, y: 272, w: 145, h: 145, label: true },
    61: { sheet: 'sheet2', x: 402, y: 272, w: 145, h: 145, label: true },
    62: { sheet: 'sheet2', x: 402, y: 272, w: 145, h: 145, label: true },
    63: { sheet: 'sheet2', x: 402, y: 272, w: 145, h: 145, label: true },
    64: { sheet: 'sheet2', x: 402, y: 272, w: 145, h: 145, label: true },
    65: { sheet: 'sheet2', x: 402, y: 272, w: 145, h: 145, label: true },
    66: { sheet: 'sheet2', x: 578, y: 272, w: 145, h: 145, label: true },
    67: { sheet: 'sheet2', x: 578, y: 272, w: 145, h: 145, label: true },
    68: { sheet: 'sheet2', x: 578, y: 272, w: 145, h: 145, label: true },
    69: { sheet: 'sheet2', x: 578, y: 272, w: 145, h: 145, label: true },
    70: { sheet: 'sheet2', x: 578, y: 272, w: 145, h: 145, label: true },
    71: { sheet: 'sheet2', x: 752, y: 272, w: 145, h: 145, label: true },
    72: { sheet: 'sheet2', x: 752, y: 272, w: 145, h: 145, label: true },
    73: { sheet: 'sheet2', x: 752, y: 272, w: 145, h: 145, label: true },
    74: { sheet: 'sheet2', x: 752, y: 272, w: 145, h: 145, label: true },
    75: { sheet: 'sheet2', x: 752, y: 272, w: 145, h: 145, label: true },
    76: { sheet: 'sheet2', x: 51, y: 489, w: 148, h: 148, label: true },
    77: { sheet: 'sheet2', x: 51, y: 489, w: 148, h: 148, label: true },
    78: { sheet: 'sheet2', x: 51, y: 489, w: 148, h: 148, label: true },
    79: { sheet: 'sheet2', x: 51, y: 489, w: 148, h: 148, label: true },
    80: { sheet: 'sheet2', x: 51, y: 489, w: 148, h: 148, label: true },
    81: { sheet: 'sheet2', x: 227, y: 489, w: 148, h: 148, label: true },
    82: { sheet: 'sheet2', x: 227, y: 489, w: 148, h: 148, label: true },
    83: { sheet: 'sheet2', x: 227, y: 489, w: 148, h: 148, label: true },
    84: { sheet: 'sheet2', x: 227, y: 489, w: 148, h: 148, label: true },
    85: { sheet: 'sheet2', x: 227, y: 489, w: 148, h: 148, label: true },
    86: { sheet: 'sheet2', x: 403, y: 489, w: 148, h: 148, label: true },
    87: { sheet: 'sheet2', x: 403, y: 489, w: 148, h: 148, label: true },
    88: { sheet: 'sheet2', x: 403, y: 489, w: 148, h: 148, label: true },
    89: { sheet: 'sheet2', x: 403, y: 489, w: 148, h: 148, label: true },
    90: { sheet: 'sheet2', x: 403, y: 489, w: 148, h: 148, label: true },
    91: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    92: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    93: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    94: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    95: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    96: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    97: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    98: { sheet: 'sheet2', x: 580, y: 489, w: 148, h: 148, label: true },
    99: { sheet: 'sheet2', x: 755, y: 489, w: 148, h: 148, label: true },
    100: { sheet: 'sheet2', x: 391, y: 679, w: 200, h: 200, label: true }
    }
  },

  ROLE_POOL_CATS: ['Strimersy', 'Cake', 'Puddingi', 'Muszle'],

  PORTRAIT_MAP: {
    'The Trapper': 'https://deadbydaylight.wiki.gg/images/K01_TheTrapper_Portrait.png',
    'The Wraith': 'https://deadbydaylight.wiki.gg/images/K02_TheWraith_Portrait.png',
    'The Hillbilly': 'https://deadbydaylight.wiki.gg/images/K03_TheHillbilly_Portrait.png',
    'The Nurse': 'https://deadbydaylight.wiki.gg/images/K04_TheNurse_Portrait.png',
    'The Shape': 'https://deadbydaylight.wiki.gg/images/K05_TheShape_Portrait.png',
    'The Hag': 'https://deadbydaylight.wiki.gg/images/K06_TheHag_Portrait.png',
    'The Doctor': 'https://deadbydaylight.wiki.gg/images/K07_TheDoctor_Portrait.png',
    'The Huntress': 'https://deadbydaylight.wiki.gg/images/K08_TheHuntress_Portrait.png',
    'The Cannibal': 'https://deadbydaylight.wiki.gg/images/K09_TheCannibal_Portrait.png',
    'The Nightmare': 'https://deadbydaylight.wiki.gg/images/K10_TheNightmare_Portrait.png',
    'The Pig': 'https://deadbydaylight.wiki.gg/images/K11_ThePig_Portrait.png',
    'The Clown': 'https://deadbydaylight.wiki.gg/images/K12_TheClown_Portrait.png',
    'The Spirit': 'https://deadbydaylight.wiki.gg/images/K13_TheSpirit_Portrait.png',
    'The Legion': 'https://deadbydaylight.wiki.gg/images/K14_TheLegion_Portrait.png',
    'The Plague': 'https://deadbydaylight.wiki.gg/images/K15_ThePlague_Portrait.png',
    'The Ghost Face': 'https://deadbydaylight.wiki.gg/images/K16_TheGhostFace_Portrait.png',
    'The Demogorgon': 'https://deadbydaylight.wiki.gg/images/K17_TheDemogorgon_Portrait.png',
    'The Oni': 'https://deadbydaylight.wiki.gg/images/K18_TheOni_Portrait.png',
    'The Deathslinger': 'https://deadbydaylight.wiki.gg/images/K19_TheDeathslinger_Portrait.png',
    'The Executioner': 'https://deadbydaylight.wiki.gg/images/K20_TheExecutioner_Portrait.png',
    'The Blight': 'https://deadbydaylight.wiki.gg/images/K21_TheBlight_Portrait.png',
    'The Twins': 'https://deadbydaylight.wiki.gg/images/K22_TheTwins_Portrait.png',
    'The Trickster': 'https://deadbydaylight.wiki.gg/images/K23_TheTrickster_Portrait.png',
    'The Nemesis': 'https://deadbydaylight.wiki.gg/images/K24_TheNemesis_Portrait.png',
    'The Cenobite': 'https://deadbydaylight.wiki.gg/images/K25_TheCenobite_Portrait.png',
    'The Artist': 'https://deadbydaylight.wiki.gg/images/K26_TheArtist_Portrait.png',
    'The Onryo': 'https://deadbydaylight.wiki.gg/images/K27_TheOnryo_Portrait.png',
    'The Dredge': 'https://deadbydaylight.wiki.gg/images/K28_TheDredge_Portrait.png',
    'The Mastermind': 'https://deadbydaylight.wiki.gg/images/K29_TheMastermind_Portrait.png',
    'The Knight': 'https://deadbydaylight.wiki.gg/images/K30_TheKnight_Portrait.png',
    'The Skull Merchant': 'https://deadbydaylight.wiki.gg/images/K31_TheSkullMerchant_Portrait.png',
    'The Singularity': 'https://deadbydaylight.wiki.gg/images/K32_TheSingularity_Portrait.png',
    'The Xenomorph': 'https://deadbydaylight.wiki.gg/images/K33_TheXenomorph_Portrait.png',
    'The Good Guy': 'https://deadbydaylight.wiki.gg/images/K34_TheGoodGuy_Portrait.png',
    'The Unknown': 'https://deadbydaylight.wiki.gg/images/K35_TheUnknown_Portrait.png',
    'The Lich': 'https://deadbydaylight.wiki.gg/images/K36_TheLich_Portrait.png',
    'The Dark Lord': 'https://deadbydaylight.wiki.gg/images/K37_TheDarkLord_Portrait.png',
    'The Houndmaster': 'https://deadbydaylight.wiki.gg/images/K38_TheHoundmaster_Portrait.png',
    'The Ghoul': 'https://deadbydaylight.wiki.gg/images/K39_TheGhoul_Portrait.png',
    'The Animatronic': 'https://deadbydaylight.wiki.gg/images/K40_TheAnimatronic_Portrait.png',
    'The Krasue': 'https://deadbydaylight.wiki.gg/images/K41_TheKrasue_Portrait.png',
    'The First': 'https://deadbydaylight.wiki.gg/images/K42_TheFirst_Portrait.png',
    'The Slasher': 'https://deadbydaylight.wiki.gg/images/K43_TheSlasher_Portrait.png',
    'The Judgment': 'https://deadbydaylight.wiki.gg/images/K44_TheJudgment_Portrait.png',
    'Dwight Fairfield': 'https://deadbydaylight.wiki.gg/images/S01_DwightFairfield_Portrait.png',
    'Meg Thomas': 'https://deadbydaylight.wiki.gg/images/S02_MegThomas_Portrait.png',
    'Claudette Morel': 'https://deadbydaylight.wiki.gg/images/S03_ClaudetteMorel_Portrait.png',
    'Jake Park': 'https://deadbydaylight.wiki.gg/images/S04_JakePark_Portrait.png',
    'Nea Karlsson': 'https://deadbydaylight.wiki.gg/images/S05_NeaKarlsson_Portrait.png',
    'William Bill Overbeck': 'https://deadbydaylight.wiki.gg/images/S08_BillOverbeck_Portrait.png',
    'David King': 'https://deadbydaylight.wiki.gg/images/S10_DavidKing_Portrait.png',
    'Laurie Strode': 'https://deadbydaylight.wiki.gg/images/S06_LaurieStrode_Portrait.png',
    'Ace Visconti': 'https://deadbydaylight.wiki.gg/images/S07_AceVisconti_Portrait.png',
    'Feng Min': 'https://deadbydaylight.wiki.gg/images/S09_FengMin_Portrait.png',
    'Quentin Smith': 'https://deadbydaylight.wiki.gg/images/S11_QuentinSmith_Portrait.png',
    'Detective Tapp': 'https://deadbydaylight.wiki.gg/images/S12_DavidTapp_Portrait.png',
    'Kate Denson': 'https://deadbydaylight.wiki.gg/images/S13_KateDenson_Portrait.png',
    'Adam Francis': 'https://deadbydaylight.wiki.gg/images/S14_AdamFrancis_Portrait.png',
    'Jeff Johansen': 'https://deadbydaylight.wiki.gg/images/S15_JeffJohansen_Portrait.png',
    'Jane Romero': 'https://deadbydaylight.wiki.gg/images/S16_JaneRomero_Portrait.png',
    'Ash J. Williams': 'https://deadbydaylight.wiki.gg/images/S17_AshWilliams_Portrait.png',
    'Nancy Wheeler': 'https://deadbydaylight.wiki.gg/images/S18_NancyWheeler_Portrait.png',
    'Steve Harrington': 'https://deadbydaylight.wiki.gg/images/S19_SteveHarrington_Portrait.png',
    'Yui Kimura': 'https://deadbydaylight.wiki.gg/images/S20_YuiKimura_Portrait.png',
    'Zarina Kassir': 'https://deadbydaylight.wiki.gg/images/S21_ZarinaKassir_Portrait.png',
    'Cheryl Mason': 'https://deadbydaylight.wiki.gg/images/S22_CherylMason_Portrait.png',
    'Felix Richter': 'https://deadbydaylight.wiki.gg/images/S23_FelixRichter_Portrait.png',
    'Élodie Rakoto': 'https://deadbydaylight.wiki.gg/images/S24_ElodieRakoto_Portrait.png',
    'Yun-Jin Lee': 'https://deadbydaylight.wiki.gg/images/S25_LeeYun-jin_Portrait.png',
    'Jill Valentine': 'https://deadbydaylight.wiki.gg/images/S26_JillValentine_Portrait.png',
    'Leon Scott Kennedy': 'https://deadbydaylight.wiki.gg/images/S27_LeonScottKennedy_Portrait.png',
    'Mikaela Reid': 'https://deadbydaylight.wiki.gg/images/S28_MikaelaReid_Portrait.png',
    'Jonah Vasquez': 'https://deadbydaylight.wiki.gg/images/S29_JonahVasquez_Portrait.png',
    'Yoichi Asakawa': 'https://deadbydaylight.wiki.gg/images/S30_YoichiAsakawa_Portrait.png',
    'Haddie Kaur': 'https://deadbydaylight.wiki.gg/images/S31_HaddieKaur_Portrait.png',
    'Ada Wong': 'https://deadbydaylight.wiki.gg/images/S32_AdaWong_Portrait.png',
    'Rebecca Chambers': 'https://deadbydaylight.wiki.gg/images/S33_RebeccaChambers_Portrait.png',
    'Vittorio Toscano': 'https://deadbydaylight.wiki.gg/images/S34_VittorioToscano_Portrait.png',
    'Thalita Lyra': 'https://deadbydaylight.wiki.gg/images/S35_ThalitaLyra_Portrait.png',
    'Renato Lyra': 'https://deadbydaylight.wiki.gg/images/S36_RenatoLyra_Portrait.png',
    'Gabriel Soma': 'https://deadbydaylight.wiki.gg/images/S37_GabrielSoma_Portrait.png',
    'Nicolas Cage': 'https://deadbydaylight.wiki.gg/images/S38_NicolasCage_Portrait.png',
    'Ellen Ripley': 'https://deadbydaylight.wiki.gg/images/S39_EllenRipley_Portrait.png',
    'Alan Wake': 'https://deadbydaylight.wiki.gg/images/S40_AlanWake_Portrait.png',
    'Sable Ward': 'https://deadbydaylight.wiki.gg/images/S41_SableWard_Portrait.png',
    'Aestri Yazar': 'https://deadbydaylight.wiki.gg/images/S42_TheTroupe_Portrait.png',
    'Lara Croft': 'https://deadbydaylight.wiki.gg/images/S43_LaraCroft_Portrait.png',
    'Trevor Belmont': 'https://deadbydaylight.wiki.gg/images/S44_TrevorBelmont_Portrait.png',
    'Taurie Cain': 'https://deadbydaylight.wiki.gg/images/S45_TaurieCain_Portrait.png',
    'Orela Rose': 'https://deadbydaylight.wiki.gg/images/S46_OrelaRose_Portrait.png',
    'Rick Grimes': 'https://deadbydaylight.wiki.gg/images/S47_RickGrimes_Portrait.png',
    'Michonne Grimes': 'https://deadbydaylight.wiki.gg/images/S48_MichonneGrimes_Portrait.png',
    'Vee Boonyasak': 'https://deadbydaylight.wiki.gg/images/S49_VeeBoonyasak_Portrait.png',
    'Dustin Henderson': 'https://deadbydaylight.wiki.gg/images/S50_DustinHenderson_Portrait.png',
    'Eleven': 'https://deadbydaylight.wiki.gg/images/S51_Eleven_Portrait.png',
    'Kwon Tae-Young': 'https://deadbydaylight.wiki.gg/images/S52_KwonTae-young_Portrait.png',
    'Shane Wiigwaas': 'https://deadbydaylight.wiki.gg/images/S53_ShaneWiigwaas_Portrait.png',
    'Aurora Stardotter': 'https://deadbydaylight.wiki.gg/images/S54_AuroraStardotter_Portrait.png'
  }
};
